export { default as Admin } from "./icon-admin.svg"
export { default as Billing } from "./icon-billing.svg"
export { default as Email } from "./icon-email.svg"
export { default as Exams } from "./icon-exam.svg"
export { default as Feature } from "./icon-feature.svg"
export { default as Dashboard } from "./icon-home.svg"
export {default as Logo} from "./Ellipse 6.png"
export { default as Phone } from "./icon-phone.svg"
export { default as Setting } from "./icon-setting.svg"
export { default as Student } from "./icon-student.svg"
export { default as AddClass } from "./icon-add-class.svg"
export { default as AddStudent } from "./icon-add-student.svg"
export {default as Active} from "./icon-active.svg"
export {default as Teacher} from "./icon-teacher.svg"
export {default as Search} from "./icon-search.svg"
