export { default as admin } from "./icon-admin.svg"
export { default as billing } from "./icon-billing.svg"
export { default as email } from "./icon-email.svg"
export { default as exams } from "./icon-exam.svg"
export { default as feature } from "./icon-feature.svg"
export { default as dashboard } from "./icon-home.svg"
export {default as logo} from "./Ellipse 6.png"
export { default as phone } from "./icon-phone.svg"
export { default as setting } from "./icon-setting.svg"
export { default as student } from "./icon-student.svg"
export { default as addClass } from "./icon-add-class.svg"
export { default as addStudent } from "./icon-add-student.svg"
export {default as active} from "./icon-active.svg"
export {default as teacher} from "./icon-teacher.svg"
export {default as search} from "./icon-search.svg"
export {default as close} from "./icon-close.svg"
export {default as dropdown} from "./icon-dropdown.svg"
export {default as mention} from "./icon-notify.svg"
